test/integration: Add `__always_inline` to `task_state` in `linux-6.17.0/shadow-pid.patch`
From `build.log`:

```
ERROR: function task_state doesn't have patchable function entry, unable to patch
ERROR: fs/proc/array.o: 1 function(s) can not be patched
create-diff-object: unreconcilable difference
```

This is similar to the [1] discussion. So in this case the compiler did
not inlined `task_state`, and since inline implies notrace, it don't
have fentry/mcount. Forcing it to be inline solves this.

[1]: https://lore.kernel.org/all/CAPhsuW58LYU8iRCjoeChCyQ_7gqZvp6_U-fJr2Crf6gOniA51g@mail.gmail.com/

Signed-off-by: Pablo Alessandro Santos Hugen <phugen@redhat.com>