kpatch-build: fix ppc64le trampoline handling after BPF changes
Starting from linux commit eec37961a56a (powerpc64/ftrace: Move
ftrace sequence out of line) the kpatch-build fails

	Extracting new and modified ELF sections
	create-diff-object: ERROR: fs/proc/cmdline.o: kpatch_create_ftrace_callsite_sections: 3860: cmdline_proc_show: unexpected instruction in patch section of function

	fs/proc/cmdline.o: changed function: cmdline_proc_show
	doing "deep find" for parent object
	ERROR: invalid ancestor arch/powerpc/tools/vmlinux.arch.o for arch/powerpc/tools/vmlinux.arch.o. Check /root/.kpatch/build.log for more details.

Moving the ftrace stubs out-of-line modified the prologue on ppc64le
and it now uses a single nop instead of two.
Update the nop check in create-diff-object.c accordingly.

Also add vmlinux.arch.o to the list of objects excluded from
instrumentation, since it only contains the out-of-line ftrace stubs
for vmlinux.
The module loader will create any necessary (livepatch) module
ftrace stubs, so we don't care about modifications to this file.

Closes: #1470 ("cs-10: ppc64le builds fail")
Reported-by: Joe Lawrence <joe.lawrence@redhat.com>
Signed-off-by: Radomir Vrbovsky <rvrbovsk@redhat.com>